using UnityEngine;
using PixelCrushers.QuestMachine;

/// <summary>
/// Attached to the Boss Prefab.
/// Automatically instantiates and activates the DragonBrain Quest Machine instance upon spawn.
/// Cleans it up upon death.
/// </summary>
public class DragonBrainController : MonoBehaviour
{
    [Header("Quest Configuration")]
    [Tooltip("The DragonBrain Quest asset generated by the editor script.")]
    public Quest dragonBrainAsset;

    private Quest runtimeQuestInstance;

    private void Start()
    {
        if (dragonBrainAsset == null)
        {
            Debug.LogError("[DragonBrainController] Missing DragonBrain Quest asset! The boss has no brain.");
            return;
        }

        // Clone the quest asset so multiple dragons don't share state
        runtimeQuestInstance = dragonBrainAsset.Clone();

        // Add it to the global Quest Journal or a local invisible journal for this entity
        QuestJournal journal = GetComponent<QuestJournal>();
        if (journal == null)
        {
            journal = gameObject.AddComponent<QuestJournal>();
        }

        journal.AddQuest(runtimeQuestInstance);

        // Force the quest to become active immediately (Starting the Start -> Orchestrator flow)
        runtimeQuestInstance.SetState(QuestState.Active);
        Debug.Log($"[DragonBrainController] Activated Quest Machine brain for {gameObject.name}");
    }

    private void OnDestroy()
    {
        if (runtimeQuestInstance != null)
        {
            // Cleanly shut down the quest graph when the dragon despawns/dies
            runtimeQuestInstance.SetState(QuestState.Successful);
            Debug.Log($"[DragonBrainController] Shut down Quest Machine brain for {gameObject.name}");
        }
    }
}
